default_platform(:ios)

platform :ios do
  desc "Upload a new build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    build_number = latest_testflight_build_number
    increment_build_number(build_number: build_number + 1)

    match(type: "appstore")
    gym(output_directory: "Build")
    pilot(skip_submission: true, skip_waiting_for_build_processing: true)

    reset_git_repo(skip_clean: true)
    push_to_git_remote
  end
end
