default_platform(:ios)

platform :ios do
  desc "Upload a new build to TestFlight"
  lane :beta do
    sigh
    match(type: "appstore")
    gym(output_directory: "Build")
    pilot(skip_submission: true, skip_waiting_for_build_processing: true)
  end
end
